const Configuracion = {
  icono: "",
  contenido: {
    encabezado: {
      saludo: "Explora",
      nombre01: "Mis",
      nombre02: "Proyectos",
      datos: {
        ciudad: "Antofagasta, Chile",
        correo: "alfredoa_gestay@outlook.com",
        github: "MrMonkey09",
      },
    },
    proyectos: [
      {
        id: 1,
        titulo: "Proyecto Uno",
        descripcion: "Descripción del proyecto uno.",
        enlace: "https://github.com/MrMonkey09/proyecto-uno",
        tecnologias: ["JavaScript", "React", "CSS"],
        imagen: "/assets/images/iconos/calendario.svg",
      },
      {
        id: 2,
        titulo: "Proyecto Dos",
        descripcion: "Descripción del proyecto dos.",
        enlace: "https://github.com/MrMonkey09/proyecto-dos",
        tecnologias: ["Node.js", "Express", "MongoDB"],
        imagen: "/assets/images/iconos/calendario.svg",
      },
      {
        id: 3,
        titulo: "Proyecto Tres",
        descripcion: "Descripción del proyecto tres.",
        enlace: "https://github.com/MrMonkey09/proyecto-tres",
        tecnologias: ["Python", "Django", "PostgreSQL"],
        imagen: "/assets/images/iconos/calendario.svg",
      },
      {
        id: 3,
        titulo: "Proyecto Tres",
        descripcion: "Descripción del proyecto tres.",
        enlace: "https://github.com/MrMonkey09/proyecto-tres",
        tecnologias: ["Python", "Django", "PostgreSQL"],
        imagen: "/assets/images/iconos/calendario.svg",
      },
      {
        id: 3,
        titulo: "Proyecto Tres",
        descripcion: "Descripción del proyecto tres.",
        enlace: "https://github.com/MrMonkey09/proyecto-tres",
        tecnologias: ["Python", "Django", "PostgreSQL"],
        imagen: "/assets/images/iconos/calendario.svg",
      },
      {
        id: 3,
        titulo: "Proyecto Tres",
        descripcion: "Descripción del proyecto tres.",
        enlace: "https://github.com/MrMonkey09/proyecto-tres",
        tecnologias: ["Python", "Django", "PostgreSQL"],
        imagen: "/assets/images/iconos/calendario.svg",
      },
      {
        id: 3,
        titulo: "Proyecto Tres",
        descripcion: "Descripción del proyecto tres.",
        enlace: "https://github.com/MrMonkey09/proyecto-tres",
        tecnologias: ["Python", "Django", "PostgreSQL"],
        imagen: "/assets/images/iconos/calendario.svg",
      },
      {
        id: 3,
        titulo: "Proyecto Tres",
        descripcion: "Descripción del proyecto tres.",
        enlace: "https://github.com/MrMonkey09/proyecto-tres",
        tecnologias: ["Python", "Django", "PostgreSQL"],
        imagen: "/assets/images/iconos/calendario.svg",
      },
      {
        id: 3,
        titulo: "Proyecto Tres",
        descripcion: "Descripción del proyecto tres.",
        enlace: "https://github.com/MrMonkey09/proyecto-tres",
        tecnologias: ["Python", "Django", "PostgreSQL"],
        imagen: "/assets/images/iconos/calendario.svg",
      },
      {
        id: 3,
        titulo: "Proyecto Tres",
        descripcion: "Descripción del proyecto tres.",
        enlace: "https://github.com/MrMonkey09/proyecto-tres",
        tecnologias: ["Python", "Django", "PostgreSQL"],
        imagen: "/assets/images/iconos/calendario.svg",
      },
    ],
  },
};

export default Configuracion;
